### ISSUE TITLE
Add support for pathlib Paths

### ISSUE THREAD

**Issue by Jonxslays** [parafoxia/len8#6]
**Is your feature request related to a problem? Please describe.**
A description of what the problem is. Ex. What are you trying to solve?

After dropping support for Python 3.2-3.5 we can now take advantage of `pathlib` in all its glory.

**Describe the solution you'd like**
A detailed description of an ideal implementation.

Current path arguments that expect a `str` should be modified to accept `str` or `Path`, and os.path calls replaced.

**Comment by parafoxia** [comment]
Working on this now.
